# Generated by Django 3.0.4 on 2020-03-31 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_profle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profle',
        ),
    ]
